# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker build -t docker-powershell .
        docker images
        docker run --name test-container -t -d docker-powershell 
        docker exec test-container pwsh -command 'Get-Module -Name psake -ListAvailable'
        docker exec test-container pwsh -command 'Get-Module -Name Pester -ListAvailable'
        docker exec test-container pwsh -command 'Get-Module -Name PSScriptAnalyzer -ListAvailable'
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Build then test docker container