# PowerShell CI Container build
# Build and test PowerShell CI container

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        set -e
        docker build -t docker-powershell .
        docker images
        docker run --name test-container -t -d docker-powershell 
        docker exec test-container pwsh -command 'if(-not(Get-Module -Name "psake" -ListAvailable).Name -eq "psake"){ throw "psake not installed"}'
        docker exec test-container pwsh -command 'if(-not(Get-Module -Name "Pester" -ListAvailable).Name -eq "Pester"){ throw "Pester not installed"}'
        docker exec test-container pwsh -command 'if(-not(Get-Module -Name "PSScriptAnalyzer").Name -eq "PSScriptAnalyzer"){ throw "PSScriptAnalyzer not installed"}'
      workingDirectory: $(Build.SourcesDirectory)
      displayName: Build then test docker container