---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    base_image: mcr.microsoft.com/powershell
    image_name: 'matthewdavis111/powershell-ci'

  pre_tasks:
    - name: Pull latest PowerShell container image
      docker_image:
        name: "{{ base_image }}"
        source: pull
        force_source: true

    - name: Build Docker image from Dockerfile
      docker_image:
        name: "{{ image_name }}"
        source: build
        build:
          path: docker
          pull: false
        state: present
        push: true
